### ISSUE TITLE
The "freeze_support()" line can be omitted if the program BUG

### ISSUE THREAD

**Issue by nankaiyoutian** [pss1207/retinal_oct_classification#1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\X\202105\retinal_oct_classification-master\train.py", line 70, in <module>
    inputs, classes = next(iter(dataloaders['train']))
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\Users\hao39\anaconda3\envs\pytorch2\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''

**Comment by nankaiyoutian** [comment]
what should I do to deal with this error? 
thanks.

**Comment by nankaiyoutian** [comment]
okay, I have solved this problem by changing the param "num_worker" to 0

**Comment by nankaiyoutian** [comment]
Does this code refer to any paper?
